version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version
  build:
    commands:
      - echo Building the Maven project...
      - mvn clean install

artifacts:
  files:
    - target/*.jar
